### ISSUE TITLE
11s between file names of two integrations

### ISSUE THREAD

**Issue by yupinghuang** [lwa-project/ovro_data_recorder#11]
I'm looking at the calibration data I collected a few days a go

```
yuping@astm13:cal$ ls 20220402_1707*20MHz.ms.tar
20220402_170706_20MHz.ms.tar  20220402_170716_20MHz.ms.tar  20220402_170727_20MHz.ms.tar  20220402_170737_20MHz.ms.tar  20220402_170747_20MHz.ms.tar  20220402_170757_20MHz.ms.tar
```

It appears that the timestamp went from 20220402_170716 to 20220402_170727 (i.e. a difference of 11 seconds)?

The first ms has a timestamp `Observed from   02-Apr-2022/17:07:12.0   to   02-Apr-2022/17:07:22.0 (UTC)`
The second ms has a  timestamp `Observed from   02-Apr-2022/17:07:22.0   to   02-Apr-2022/17:07:32.0 (UTC)`

Maybe a rounding issue while naming files?

**Comment by jaycedowell** [comment]
Could be.  I think the standard integration time is ~10.03 s which could get you into that situation.  Do the timestamps in the main data table flow correctly between files?

**Comment by yupinghuang** [comment]
The timestamps I listed are from CASA's `listobs`. Is that what you mean?

Took another look at the data files. It went from 170727, 170737... to 171237, 171237, 1712**48**.

That's 5 min and 20s = 32 integrations. So I guess that makes sense?

`listobs` on 20220402_171017_47MHz.ms gives `02-Apr-2022/17:10:12.5   to   02-Apr-2022/17:10:22.6 (UTC)` which looks right.

**Comment by jaycedowell** [comment]
I was more thinking of using `browsetable` to look at the TIME and TIME_CENTROID columns.  For a couple of random files I see:
 * `20220406_001434_84MHz.ms` has a TIME of 2022-04-06-00:14:34.4843
 * `20220406_001444_84MHz.ms` has a TIME of 2022-04-06-00:14:44.5153

Those match up with integration time I expect and what is reported INTERVAL column.  I think the 11 s is just a feature of using integer seconds in the filename.
