### ISSUE TITLE
How to flag known bad inputs?

### ISSUE THREAD

**Issue by caseyjlaw** [lwa-project/ovro_data_recorder#13]
At OVRO-LWA, the f-engine client can be used to identify specific bad inputs. This may be related to a bad lane on the hardware, so it is definitely bad and should flagged in all downstream analysis.
One option is to have the data recorder take an argument for good/bad inputs and either (1) flag them or (2) ignore them. Other options exist (e.g., have CASA calibration pipeline flag some antennas/inputs and let that propagate into beamforming, etc. during application of solutions).
How hard would it be to have the data recorder flag data?

**Comment by jaycedowell** [comment]
Are you thinking "flag" as in look at the data and determine good/bad antennas or "flag" as in take in good/bad information generated somewhere else and create a mask on the visibility data?

**Comment by caseyjlaw** [comment]
The latter. We will know that some ant-pols are bad, based on real-time information. We can pass that in to the data recorder or some other system.
The question is what's the easiest way to implement an automatic bad-input flag?

**Comment by caseyjlaw** [comment]
Ideally this would also be an input to beamforming recorder, too. However, Marin noted that if the slow visibilities are flagged, then the calibration solutions are flagged and thus the application of solutions will remove them prior to summing over antennas.

**Comment by jaycedowell** [comment]
There is a flag column in the measurement set that could be used to hold the flagging so it would be straightforward to write this column with something other than all zeros.  My concerns are (1) actually getting the flagging information to the recorder/keeping those flags updated and (2) performance impacts of generating/writing the flags.

**Comment by jaycedowell** [comment]
By the time the beam recorders gets the beam data all of the flagging has been done implicitly through the beamforming coefficients.  There is really nothing left to flag unless you are starting to talk about RFI and some kind of online flagging.

**Comment by yupinghuang** [comment]
For slow vis, I think the harder part to get right is for the bad ant/pols to be stored somewhere and time tagged, which takes some thinking to figure out the use cases. After that, we can probably apply the flags as first step of processing. Flagging within the data recorder is probably not necessary and may pose quite stringent constraints on the bad ant/pol ingest and storage mechanisms (i.e. Jayce's point).

**Comment by caseyjlaw** [comment]
Good points.
To refine the point, Jack reminded me that the f-engine client already has some logic for identifying problematic inputs. Create a client instance and type:
`> lwa_feng.print_status_all(ignore_ok=True)`
It steps through each processing block and prints out values that deviate from expectations.

I like Yuping's suggestion to keep this simple. I'll create a feature request to poll the SNAP2s, convert failures into data coordinates (e.g., ant-pol), and save info.
Thanks, all!
