### ISSUE TITLE
disks filling due to old ms and ms.tar files

### ISSUE THREAD

**Issue by caseyjlaw** [lwa-project/ovro_data_recorder#16]
Copying over an issue posted by Marin on lwa-issues.
`I see that the recorder now writes .ms files instead of .ms.tar files. Is the buffer that runs on dr-vslow-1 still looking for .ms.tar files to delete by any chance? A quick scan through the recent dr-vslow-1 log files show no more of the === Quota Report === summaries on the number of files removed.`

**Comment by jaycedowell** [comment]
Looks like the underlying problem is that the size calculation ignores the contents of a directory when it is figuring out if something should be deleted.  Since the directory itself is small then the recorder never thinks there is a problem.

**Comment by jaycedowell** [comment]
@caseyjlaw @marinanderson is this working as expected now?

**Comment by marinanderson** [comment]
Yes, can verify this is working now.
