### ISSUE TITLE
Beamformed data recording and calibration issues

### ISSUE THREAD

**Issue by iveydavis** [lwa-project/ovro_data_recorder#17]
This is a long one. The TL;DR: for three simultaneous beams, beam 1's log is reporting widely variable (up/down to -200%) missing data fractions, beams 2 and 3 not actually writing to file. Calibration re-runs on the 32nd pipeline every time I assign a target to a beam.

I tried to do some drift scans using beams 1, 2 and 3. The logs show that for beams 2 and 3 that it starts files when I start recording data, but HDF5Writer is never called and so there's no output files for them. Beam 1 shows a varying missing data fraction, starting at 27.355% and eventually reaching -200% for my test in the afternoon, and there are no missing data fractions reported for beams 2 or 3 at all (not even to say 0%). The file for beam 1 is just an array of 0s.
As far as I can tell, I followed the system use recipe as I usually do:
```
from lwa352_pipeline_control import Lwa352CorrelatorControl
p = Lwa352CorrelatorControl( [‘lxdlwagpu0%d’ % i for i in range(1,9) ], npipeline_per_host=4)
p.stop_pipelines()
p.start_pipelines() 
p.pipelines_are_up(verbose = True)
p.configure_corr(dest_ip=[’10.41.0.25’, ’10.41.0.25’, ’10.41.0.73’, ’10.41.0.73’], dest_port=[10001+i//4 for i in range(32)] )
```
I ran the following block of commands in three separate terminals so that I could set the positions of the three different beams as quickly as possible before starting the data recording (c1 would be replaced with e.g. c2 for beam 2 etc):
```
from mnc.xengine_beamformer_control import *
import glob
calfiles = glob.glob(‘/home/ubuntu/mmanders/caltables/latest/*.bcal’)
c1 = BeamPointingControl(1)
for calfile in calfiles: 
       try: 
           c1.set_beam_calibration(calfile) 
       except Exception as e: 
           print(“ERROR: %s” % str(e)) 
c1.set_beam_dest()
c1.set_beam_pointing(0,90)
```
when I would run `set_beam_pointing`, I would get the following response:
![Screenshot from 2022-07-20 07-32-10](https://user-images.githubusercontent.com/29830471/180076817-88ad6434-a406-437b-a4a0-41a1429e262d.png)
The warning about "suspect calibration" isn't unusual, but the re-calibration of the 32nd pipeline is a new feature. It happened for each beam *every time* I would assign a target to point at. 
Following this, I ran the typical data recording commands:
```
from mnc.ezdr import Lwa352RecorderControl
d = Lwa352RecorderControl(‘power’)
d..record(duration = 60)
``` 
The first time I ran this this morning, I ran this last block in the same terminal I set up beam 3. When I reproduced the issue this afternoon, I ran it in the same terminal I set up beam 1.

**Comment by jaycedowell** [comment]
Are you running these commands on gpu09 or one of the cal/im nodes?

**Comment by iveydavis** [comment]
> Are you running these commands on gpu09 or one of the cal/im nodes?

gpu09

**Comment by jaycedowell** [comment]
`from mnc.xengine_beamformer_control import *`?  I alway use the version in `ovro_data_recorder` since that is where my active development is.

**Comment by jaycedowell** [comment]
FYI: I'm giving it a shot now.  The `ovro_data_recorder` one.

**Comment by jaycedowell** [comment]
Everything seems ok.  I brought up and calibrated beams 1 through 3.  The data are flowing to the recorders.

**Comment by iveydavis** [comment]
I think `from mnc.xengine_beamformer_control import *` is what I ran the last time I had successful beamformed observations (June 10th). I guess we should update the system use recipe? or try to figure out where the methods in ovro_data_recorder and mnc diverge?

**Comment by jaycedowell** [comment]
This is mnc vs ovro_data_recorder is kind of an open question right now.  It would be good for xengine_beamformer_control to move there but it needs to stabilize first.  Personally, I'd rather people be using run_sdf.py but that needs some testing which I haven't been able to get around to.

**Comment by caseyjlaw** [comment]
I'll copy in the latest version of x_engine_beamformer_control to mnc for now. Should prevent this particular issue.
