### ISSUE TITLE
dr4 not fully operational: Only 12 of 9 threads active

### ISSUE THREAD

**Issue by yupinghuang** [lwa-project/ovro_data_recorder#24]
saw this on a few different data recorders at different times and the warning tends to persist for a while

```
'WARNING: dr4 not fully operational: Only 12 of 9 threads active - MainThread,etcd3_watch_7fa2eb3d2b70,Thread-1,Thread-2,CaptureOp,SpectraOp,StatisticsOp,WriterOp,GlobalLogger,PerformanceLogger,StorageLogger,StatusLogger'
```

This is more of a question: etcd3_watch_7fa2eb3d2b70,Thread-1,Thread-2 -- do these threads not finishing suggest more of an issue talking to etcd than the data recorder doing something wrong?

**Comment by jaycedowell** [comment]
There has always been some funniness with the etcd stuff.  There is that "watch" thread which deals with the callbacks for the commands but I'm not sure what "Thread-1" and "Thread-2" are about.  I had tried to [deal with these extra threads like inflating the thread count](https://github.com/lwa-project/ovro_data_recorder/blob/main/dr_beam.py#L581) but maybe my counting is off after I split the different loggers into their own threads.

The other funniness with etcd is that there is some kind of exit hang that happens with the `mnc.mcs.Client` class that all of this uses.  It's really annoying but I have no idea where it comes from.

**Comment by yupinghuang** [comment]
I was looking through the python etcd3 docs and apparently https://github.com/ovro-lwa/mnc_python/blob/main/mnc/mcs.py#L429 does not acquire the lock unless one calls `lock.acquire()'.

It does have a transaction semantic tho but it's kind of ugly....

If you do decide to actually lock. Looks like only the manifest key needs to be locked?

**Comment by jaycedowell** [comment]
Seems to be working.
