### ISSUE TITLE
high load average after dr-managers running for a while

### ISSUE THREAD

**Issue by yupinghuang** [lwa-project/ovro_data_recorder#31]
saw a load average of ~60 on calim01. Looked like each of dr-managers was using 5 cores according to top. After restarting dr-manager-vfast the load average decreased and after restarting dr-manager-vslow it decreases further.

```
(base) [yuping@lwacalim01 ~]$ w
 23:41:21 up 46 days,  1:55,  3 users,  load average: 57.82, 59.58, 61.02
 
# restarted dr-manager-vfast

 (base) [pipeline@lwacalim01 user]$ w
 23:51:05 up 46 days,  2:05,  4 users,  load average: 48.27, 57.84, 59.65
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
idavis   pts/0    10.40.0.4        15:34    7:57   1:52   1:52  /opt/devel/idavis/conda/development/bin/python /opt/devel/idavis/conda/development/bin/ipython
pipeline pts/1    10.40.0.4        23:47    0.00s  0.07s  0.01s w
yuping   pts/2    10.40.0.4        23:49   56.00s  0.04s  0.04s -bash
bin.chen pts/5    10.40.0.4        21:45    2:05m  0.04s  0.04s -bash

#restarted dr-manager-vslow

(base) [pipeline@lwacalim01 user]$ w
 23:54:37 up 46 days,  2:08,  4 users,  load average: 3.25, 31.56, 48.93
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
idavis   pts/0    10.40.0.4        15:34   11:29   1:53   1:52  /opt/devel/idavis/conda/development/bin/python /opt/devel/idavis/conda/development/bin/ipython
pipeline pts/1    10.40.0.4        23:47    2.00s  0.08s  0.01s w
yuping   pts/2    10.40.0.4        23:49    4:28   0.04s  0.04s -bash
bin.chen pts/5    10.40.0.4        21:45    2:08m  0.04s  0.04s -bash
```

**Comment by jaycedowell** [comment]
The managers do so little.  They mainly poll the DRs that they manage and come up with an overall state.  That state gets sent over to etcd.  Maybe it has something to do with the etcd interfacing?

**Comment by jaycedowell** [comment]
It could be from the `send_command()` function that creates its own instance of an `etcd3.Etcd3Client` each time it is called.  https://github.com/lwa-project/ovro_data_recorder/commit/60316e3e59069c26dd7d3de335332dff1a2a1f64 and https://github.com/lwa-project/ovro_data_recorder/commit/426f2ce1005c2ddac8c11f457c1150c50dace531 try to address this by `close()`-ing out the client before returning.

**Comment by caseyjlaw** [comment]
Rick's preferred way to use the key-value store is with the DsaStore, so:
```
from dsautils import dsa_store
ds = dsa_store.DsaStore()
ds.get_dict(...)
```

This should abstract handle open/close and abstract the underlying library, so we can change it, if needed.

**Comment by yupinghuang** [comment]
Been looking great!
