### ISSUE TITLE
3.2 GB dr-beam1 syslog file

### ISSUE THREAD

**Issue by yupinghuang** [lwa-project/ovro_data_recorder#32]
```
3.2G -rw-------.  1 root     root      3.2G May  9 20:15 dr-beam-1.lwacalim01.syslog
```

```
(base) [yuping@lwacalim01 log]$ sudo tail dr-beam-1.lwacalim01.syslog
May  9 20:15:18 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:18 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
May  9 20:15:19 lwacalim01 dr-beam-1[460178]: Breaking from packet receive because of so many late packets
```

**Comment by caseyjlaw** [comment]
Looking back through the logs, I see this state started at 2023-05-03 19:27:24, but quickly logged "error condition cleared". This happened as a beamforming observation started. This cycle repeated a couple hours later. At some later point, the error logging started and did not get cleared.
A full x-engine restart was required to keep this from recurring.

**Comment by jaycedowell** [comment]
This "Breaking from packet receive ..." message comes from the Bifrost library.  It's telling us that it is expecting to see packets from sequence numbers near `s` but it has received one with a sequence number `<< s`.  This could either be from some kind of time keeping problem on the sender side or some kind of corruption in the packet that causes the sequence number to be wrong (either in the current packet or a previous packet that was used to set `s`).

**Comment by jaycedowell** [comment]
The syslog file is no more.
