### ISSUE TITLE
Support for the "Fast Visibilties" Mode

### ISSUE THREAD

**Issue by jaycedowell** [lwa-project/ovro_data_recorder#6]
Add support to either `dr_visibitlies.py` or a new script to record the fast visibilities on demand.

**Comment by jaycedowell** [comment]
Also linked with #4 at some level since this is a scheduled operation.

**Comment by jaycedowell** [comment]
02dcaa3 makes some progress towards addressing this but there is a baseline counting problem for the "fast mode".  Maybe the easiest thing to do is to sub-select the `station.ovro` instance to only include the antennas that come out with fast?

**Comment by jaycedowell** [comment]
Recent work with the fast visibility recorder shows that some thought is needed to figuring out how to better deal with dynamic changes to what the x engines send out.

**Comment by jaycedowell** [comment]
The [fastvis_ordering](https://github.com/lwa-project/ovro_data_recorder/tree/fastvis_ordering) branch should help with this last point.

**Comment by caseyjlaw** [comment]
I'm seeing the data recorders falling behind quickly after starting `drvf` recording. Would you like me to open an issue for this?

**Comment by jaycedowell** [comment]
https://github.com/ovro-lwa/lwa-issues/issues/363

**Comment by jaycedowell** [comment]
Merging https://github.com/lwa-project/ovro_data_recorder/pull/34 should have fixed both https://github.com/ovro-lwa/lwa-issues/issues/363 as well as https://github.com/ovro-lwa/lwa-issues/issues/408.
