### ISSUE TITLE
test with lwa_antpos.station

### ISSUE THREAD

**Issue by caseyjlaw** [lwa-project/ovro_data_recorder#9]
I have reworked [lwa_antpos](https://github.com/ovro-lwa/lwa-antpos) to use the latest antenna position and cabling spreadsheet. This also includes some features to support push/pull from etcd. This is tagged [v0.4.1](https://github.com/ovro-lwa/lwa-antpos/releases/tag/0.4.1).
The design of the module `station.py` is meant to duplicate that used in `ovro_data_recorder`. If I've done this right, you could install `lwa_antpos`, import its `station.py` and everything would just work.
Could you give that a test? If the design is not consistent with your work flow, please let me know.

**Comment by jaycedowell** [comment]
I was able to get it installed with a `pip install git+https://github.com/ovro-lwa/lwa-antpos.git@79ea821af9feb0cb29c1fda735647b52b06704a9` but it's complaining about `dsautils.cnf`.  What's the correct version of that to use?

**Comment by caseyjlaw** [comment]
Ah, that refers to this one: https://github.com/dsa110/dsa110-pyutils/tree/development/dsautils. Try installing this development branch and see if it can import.

**Comment by jaycedowell** [comment]
After a `pip install git+https://github.com/dsa110/dsa110-pyutils.git@9028fd74e3e9f30f74b7de3cc8924e25e5b3c2c0` the visibility pipeline now runs without throwing any fatal exceptions.

**Comment by caseyjlaw** [comment]
Great! Sorry for adding two dependencies to your code, but the goal is to centralize metadata and other parameters.
No need to push for complete integration yet, so I'll close this for now.
